exec("./NPC_Rat_King.cs");
exec("./Update_Health.cs");
exec("./Update_Speed.cs");
exec("./Update_Attack.cs");
exec("./Scratch.cs");
exec("./Add_Status.cs");
exec("./Remove_Status.cs");
exec("./Update_Foreign_Status.cs");
exec("./Spawn_Token.cs");
