function Class_Gui_List_Player_Sprite_List::onSelect(%this)
{

if (isObject(Module_Construct.ScriptObject_Player_Sprite_Module))
{

Module_Construct.ScriptObject_Player_Sprite_Module.ScriptObject_Sprite_Data.delete();

ModuleDatabase.unloadExplicit(Module_Construct.ScriptObject_Player_Sprite_Module.Module_ID_Player_Sprite_Module);

}

Module_Construct.ScriptObject_Player_Sprite_Module=Module_Construct.SimSet_Player_Sprite_Modules.getObject(%this.getSelectedItem());

ModuleDatabase.LoadExplicit(Module_Construct.ScriptObject_Player_Sprite_Module.Module_ID_Player_Sprite_Module);

Module_Construct.ScriptObject_Player_Sprite_Module.ScriptObject_Sprite_Data=
Module_Construct.ScriptObject_Player_Sprite_Module.Module_ID_Player_Sprite_Module.Player_Sprite_Load();

Module_Construct.Sprite_Player_Sprite_Preview.Visible=true;

Module_Construct.Sprite_Player_Sprite_Preview.Size=Module_Construct.ScriptObject_Player_Sprite_Module.ScriptObject_Sprite_Data.Vector_2D_Size;

Module_Construct.Sprite_Player_Sprite_Preview.Animation=Module_Construct.ScriptObject_Player_Sprite_Module.ScriptObject_Sprite_Data.Animation_Run_Down;

}
