exec("./NPC_Medic.cs");
exec("./Update_Health.cs");
exec("./Update_Speed.cs");
exec("./Update_Attack.cs");
exec("./Heal.cs");
exec("./Add_Status.cs");
exec("./Remove_Status.cs");
exec("./Update_Foreign_Status.cs");
exec("./Recuperate.cs");
